### ISSUE TITLE
displayed_notification_buttons

### ISSUE THREAD

**Issue by jag-k** [djstein/python-macos-notifications#1]
How to use displayed_notification_buttons?

**Comment by ninest** [comment]
Not sure if you're still looking for the answer, but I answered a similar question here: https://stackoverflow.com/questions/62234033/how-create-local-notification-on-macos-catalina-pyobjc

You can display buttons, but it has its limits. The code has to "continue running" for the button callbacks to work.

I quite a bit before answering that question, but it obviously isn't perfect. I was googling around and found this repo too
